
@baseUrl = http://localhost:8001
@contentType = application/json


### Health Check
GET {{baseUrl}}/health

### Info de la API
GET {{baseUrl}}/


### 1. Crear usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "nombre": "emir",
  "username": "emir",
  "contraseña": "123456",
  "pin": 1224,
  "rol": "empleado",
  "puesto": "Ingeniero"
}


### Obtener lista completa de usuarios
GET {{baseUrl}}/usuarios

### Obtener usuario con ID 1
GET {{baseUrl}}/usuarios/4


###  usuario que no exist
GET {{baseUrl}}/usuarios/999

### Actualizar PIN del usuario 1
PUT {{baseUrl}}/usuarios/2
Content-Type: {{contentType}}

{
  "rol": "admin"
}


### Actualizar 
PUT {{baseUrl}}/usuarios/3
Content-Type: {{contentType}}

{
  "nombre": "Carlos Admin ",
  "pin": 1111,
  "puesto": "Jefe de Operaciones"
}


### Autenticar adr - Contraseña correcta
POST {{baseUrl}}/usuarios/autenticar
Content-Type: {{contentType}}

{
  "username": "adrian",
  "contraseña": "123456"
}

### Autenticar adr - Contraseña incorrecta
POST {{baseUrl}}/usuarios/autenticar
Content-Type: {{contentType}}

{
  "username": "adrian",
  "contraseña": "incorrecta"
}


### Eliminar usuario con ID 2
DELETE {{baseUrl}}/usuarios/7

### Intentar eliminar usuario que no existe
DELETE {{baseUrl}}/usuarios/999
